version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3005:3005"
    volumes:
      - ./uploads:/src/uploads/:rw
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
